// Initial users for the app
export const initialUsers = [
  {
    id: 1,
    username: 'alice',
    email: 'alice@test.com',
    password: 'password123',
    avatar: 'https://i.pravatar.cc/150?img=1',
    status: 'online',
    lastSeen: new Date(),
  },
  {
    id: 2,
    username: 'bob',
    email: 'bob@test.com',
    password: 'password123',
    avatar: 'https://i.pravatar.cc/150?img=2',
    status: 'online',
    lastSeen: new Date(),
  },
  {
    id: 3,
    username: 'charlie',
    email: 'charlie@test.com',
    password: 'password123',
    avatar: 'https://i.pravatar.cc/150?img=3',
    status: 'online',
    lastSeen: new Date(),
  },
  {
    id: 4,
    username: 'diana',
    email: 'diana@test.com',
    password: 'password123',
    avatar: 'https://i.pravatar.cc/150?img=4',
    status: 'offline',
    lastSeen: new Date(Date.now() - 3600000),
  },
  {
    id: 5,
    username: 'evan',
    email: 'evan@test.com',
    password: 'password123',
    avatar: 'https://i.pravatar.cc/150?img=5',
    status: 'online',
    lastSeen: new Date(),
  },
  {
    id: 6,
    username: 'fiona',
    email: 'fiona@test.com',
    password: 'password123',
    avatar: 'https://i.pravatar.cc/150?img=6',
    status: 'offline',
    lastSeen: new Date(Date.now() - 7200000),
  },
  {
    id: 7,
    username: 'george',
    email: 'george@test.com',
    password: 'password123',
    avatar: 'https://i.pravatar.cc/150?img=7',
    status: 'online',
    lastSeen: new Date(),
  },
];

// Initial messages
export const initialMessages = [
  {
    id: 'msg1',
    conversationId: 'conv-1-2',
    senderId: 1,
    receiverId: 2,
    text: 'Hey Bob! How are you doing?',
    timestamp: new Date('2025-12-15T09:00:00'),
    read: true,
  },
  {
    id: 'msg2',
    conversationId: 'conv-1-2',
    senderId: 2,
    receiverId: 1,
    text: 'Hi Alice! I am doing great, thanks for asking!',
    timestamp: new Date('2025-12-15T09:05:00'),
    read: true,
  },
  {
    id: 'msg3',
    conversationId: 'conv-1-2',
    senderId: 1,
    receiverId: 2,
    text: 'Did you see the latest project updates?',
    timestamp: new Date('2025-12-15T09:10:00'),
    read: true,
  },
  {
    id: 'msg4',
    conversationId: 'conv-1-3',
    senderId: 1,
    receiverId: 3,
    text: 'Hey Charlie! Want to grab lunch?',
    timestamp: new Date('2025-12-15T10:00:00'),
    read: false,
  },
  {
    id: 'msg5',
    conversationId: 'conv-1-3',
    senderId: 3,
    receiverId: 1,
    text: 'Sure! How about 12:30?',
    timestamp: new Date('2025-12-15T10:05:00'),
    read: false,
  },
  {
    id: 'msg6',
    conversationId: 'conv-2-3',
    senderId: 2,
    receiverId: 3,
    text: 'Did you finish the assignment?',
    timestamp: new Date('2025-12-15T11:00:00'),
    read: true,
  },
  {
    id: 'msg7',
    conversationId: 'conv-2-3',
    senderId: 3,
    receiverId: 2,
    text: 'Yes! Just submitted it.',
    timestamp: new Date('2025-12-15T11:15:00'),
    read: true,
  },
  {
    id: 'msg8',
    conversationId: 'conv-1-4',
    senderId: 1,
    receiverId: 4,
    text: 'Hi Diana! Are you coming to the meeting?',
    timestamp: new Date('2025-12-15T08:00:00'),
    read: true,
  },
  {
    id: 'msg9',
    conversationId: 'conv-1-4',
    senderId: 4,
    receiverId: 1,
    text: 'Yes, I will be there!',
    timestamp: new Date('2025-12-15T08:10:00'),
    read: true,
  },
  {
    id: 'msg10',
    conversationId: 'conv-1-5',
    senderId: 5,
    receiverId: 1,
    text: 'Hey Alice! Can you help me with the React assignment?',
    timestamp: new Date('2025-12-15T07:00:00'),
    read: false,
  },
  {
    id: 'msg11',
    conversationId: 'conv-2-5',
    senderId: 2,
    receiverId: 5,
    text: 'Great work on the presentation!',
    timestamp: new Date('2025-12-15T14:00:00'),
    read: true,
  },
  {
    id: 'msg12',
    conversationId: 'conv-2-5',
    senderId: 5,
    receiverId: 2,
    text: 'Thank you so much!',
    timestamp: new Date('2025-12-15T14:05:00'),
    read: true,
  },
  {
    id: 'msg13',
    conversationId: 'conv-3-4',
    senderId: 3,
    receiverId: 4,
    text: 'Do you have notes from yesterday?',
    timestamp: new Date('2025-12-15T13:00:00'),
    read: true,
  },
  {
    id: 'msg14',
    conversationId: 'conv-3-4',
    senderId: 4,
    receiverId: 3,
    text: 'Yes, I will send them to you.',
    timestamp: new Date('2025-12-15T13:10:00'),
    read: true,
  },
  {
    id: 'msg15',
    conversationId: 'conv-4-5',
    senderId: 4,
    receiverId: 5,
    text: 'Are you free this weekend?',
    timestamp: new Date('2025-12-15T16:00:00'),
    read: true,
  },
  {
    id: 'msg16',
    conversationId: 'conv-4-5',
    senderId: 5,
    receiverId: 4,
    text: 'Yes! What did you have in mind?',
    timestamp: new Date('2025-12-15T16:10:00'),
    read: true,
  },
  {
    id: 'msg17',
    conversationId: 'conv-1-6',
    senderId: 1,
    receiverId: 6,
    text: 'Hi Fiona! Long time no talk.',
    timestamp: new Date('2025-12-14T18:00:00'),
    read: true,
  },
  {
    id: 'msg18',
    conversationId: 'conv-2-6',
    senderId: 6,
    receiverId: 2,
    text: 'Can you send me the file?',
    timestamp: new Date('2025-12-14T15:00:00'),
    read: true,
  },
  {
    id: 'msg19',
    conversationId: 'conv-2-6',
    senderId: 2,
    receiverId: 6,
    text: 'Sure thing!',
    timestamp: new Date('2025-12-14T15:05:00'),
    read: true,
  },
  {
    id: 'msg20',
    conversationId: 'conv-1-7',
    senderId: 7,
    receiverId: 1,
    text: 'Welcome to the messaging app!',
    timestamp: new Date('2025-12-15T06:00:00'),
    read: false,
  },
];

// Utility functions
export const generateMessageId = () =>
  `msg-${Date.now()}-${Math.random().toString(36).substr(2, 9)}`;

export const getConversationId = (userId1, userId2) => {
  const sorted = [userId1, userId2].sort((a, b) => a - b);
  return `conv-${sorted[0]}-${sorted[1]}`;
};

// Auto-response templates for simulation
export const responseTemplates = [
  "That's interesting!",
  "Tell me more!",
  "I see what you mean.",
  "Absolutely!",
  "I agree with you.",
  "That's a good point.",
  "I understand.",
  "Makes sense!",
  "For sure!",
  "Definitely!",
  "I was thinking the same thing.",
  "That sounds great!",
  "Nice!",
  "Cool!",
  "Thanks for sharing!",
  "Interesting perspective.",
  "I hadn't thought of that.",
  "Good idea!",
  "That works for me.",
  "Sounds good!",
  "Perfect!",
  "Awesome!",
  "I like that!",
  "Let me think about it.",
  "That's helpful, thanks!",
  "Appreciate it!",
  "Got it!",
  "Will do!",
  "Sure thing!",
  "No problem!",
];

export const generateAutoResponse = () => {
  const template = responseTemplates[Math.floor(Math.random() * responseTemplates.length)];
  return template;
};
